# Generated by Django 5.0.6 on 2024-06-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10)),
                ('solicitante', models.CharField(max_length=50)),
                ('contato', models.CharField(max_length=13)),
            ],
        ),
    ]
